apiVersion: scaffolder.platform.lab/v1
kind: TechnologyTemplate
metadata:
  name: node-api
  version: 3.0.0
spec:
  owner: platform-engineering
  runtime: nodejs
  port: 8080
  pipeline: default
  registry:
    provider: distribution
    image: registry:3
    publishHost: localhost:5000
    pullHost: platform-registry:5000
  delivery:
    strategy: gitops
    engine: argocd
    packaging: helm
  cluster:
    platform: kind
    context: kind-platform-lab
  ci:
    provider: github-actions
    runnerLabels: [self-hosted, linux, x64, platform-lab]
    reusableWorkflow: Danylo93/platform-pipeline-templates/.github/workflows/platform-default.yml
    revision: 88551206a068985b1801befd0fc66465eb12a228
  environments:
    - name: ti
      namespace: platform-ti
    - name: hml
      namespace: platform-hml
    - name: prod
      namespace: platform-prod
  generatedBranches:
    - main
    - deployment_files
  requiredResources:
    - Deployment
    - Service
    - Application
