apiVersion: scaffolder.platform.lab/v1
kind: TechnologyTemplate
metadata:
  name: node-api
  version: 2.0.0
spec:
  owner: platform-engineering
  runtime: nodejs
  port: 8080
  pipeline: default
  registry:
    provider: harbor
    host: harbor.local
    project: platform-lab
  delivery:
    strategy: gitops
    engine: argocd
    packaging: helm
  cluster:
    platform: openshift-local
  environments:
    - name: ti
      namespace: platform-ti
    - name: hml
      namespace: platform-hml
    - name: prod
      namespace: platform-prod
  generatedBranches:
    - master
    - deployment_files
  requiredResources:
    - Deployment
    - Service
    - Route
    - ConfigMap
